
#include "ModRegRMSchemas.h"

const ModRegRMSchema EmptyModRegRMSchema = { {Mod::_none, Size::_none}, {Reg::_none, Size::_none}, {RM::_none, Size::_none, RM::_none} };

const ModRegRMSchema ModRegRMSchemas[0x100 /*00 000 000 - 11 111 111*/] = {
	/*00 000 000*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*00 000 001*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*00 000 010*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*00 000 011*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*00 000 100*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 000 101*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 000 110*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 000 111*/ {{Mod::no_disp, Size::_none}, {Reg::A, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 001 000*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*00 001 001*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*00 001 010*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*00 001 011*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*00 001 100*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 001 101*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 001 110*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 001 111*/ {{Mod::no_disp, Size::_none}, {Reg::C, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 010 000*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*00 010 001*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*00 010 010*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*00 010 011*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*00 010 100*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 010 101*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 010 110*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 010 111*/ {{Mod::no_disp, Size::_none}, {Reg::D, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 011 000*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*00 011 001*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*00 011 010*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*00 011 011*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*00 011 100*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 011 101*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 011 110*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 011 111*/ {{Mod::no_disp, Size::_none}, {Reg::B, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 100 000*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::A,	Size::w_dword, RM::A}},
	/*00 100 001*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::C,	Size::w_dword, RM::C}},
	/*00 100 010*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::D,	Size::w_dword, RM::D}},
	/*00 100 011*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::B,	Size::w_dword, RM::B}},
	/*00 100 100*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 100 101*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 100 110*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 100 111*/ {{Mod::no_disp, Size::_none}, {Reg::SP, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 101 000*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::A,	Size::w_dword, RM::A}},
	/*00 101 001*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::C,	Size::w_dword, RM::C}},
	/*00 101 010*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::D,	Size::w_dword, RM::D}},
	/*00 101 011*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::B,	Size::w_dword, RM::B}},
	/*00 101 100*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 101 101*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 101 110*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 101 111*/ {{Mod::no_disp, Size::_none}, {Reg::BP, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 110 000*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::A,	Size::w_dword, RM::A}},
	/*00 110 001*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::C,	Size::w_dword, RM::C}},
	/*00 110 010*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::D,	Size::w_dword, RM::D}},
	/*00 110 011*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::B,	Size::w_dword, RM::B}},
	/*00 110 100*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 110 101*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 110 110*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 110 111*/ {{Mod::no_disp, Size::_none}, {Reg::SI, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*00 111 000*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::A,	Size::w_dword, RM::A}},
	/*00 111 001*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::C,	Size::w_dword, RM::C}},
	/*00 111 010*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::D,	Size::w_dword, RM::D}},
	/*00 111 011*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::B,	Size::w_dword, RM::B}},
	/*00 111 100*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*00 111 101*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::Disp,	Size::w_dword, RM::BP}},
	/*00 111 110*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::Disp}},
	/*00 111 111*/ {{Mod::no_disp, Size::_none}, {Reg::DI, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI}},

	/*01 000 000*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*01 000 001*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*01 000 010*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*01 000 011*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*01 000 100*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*01 000 101*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP}},
	/*01 000 110*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI}},
	/*01 000 111*/ {{Mod::disp,	   Size::byte}, {Reg::A, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI}},

	/*01 001 000*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*01 001 001*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*01 001 010*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*01 001 011*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*01 001 100*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*01 001 101*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP}},
	/*01 001 110*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI}},
	/*01 001 111*/ {{Mod::disp,	   Size::byte}, {Reg::C, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI}},

	/*01 010 000*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*01 010 001*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*01 010 010*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*01 010 011*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*01 010 100*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*01 010 101*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP}},
	/*01 010 110*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI}},
	/*01 010 111*/ {{Mod::disp,	   Size::byte}, {Reg::D, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI}},

	/*01 011 000*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A}},
	/*01 011 001*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C}},
	/*01 011 010*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D}},
	/*01 011 011*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B}},
	/*01 011 100*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP}},
	/*01 011 101*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP}},
	/*01 011 110*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI}},
	/*01 011 111*/ {{Mod::disp,	   Size::byte}, {Reg::B, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI}},

	/*01 100 000*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*01 100 001*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*01 100 010*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*01 100 011*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*01 100 100*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*01 100 101*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::BP,	Size::w_dword, RM::BP} },
	/*01 100 110*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::SI} },
	/*01 100 111*/{ {Mod::disp,	   Size::byte}, {Reg::SP, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI} },

	/*01 101 000*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*01 101 001*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*01 101 010*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*01 101 011*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*01 101 100*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*01 101 101*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::BP,	Size::w_dword, RM::BP} },
	/*01 101 110*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::SI} },
	/*01 101 111*/{ {Mod::disp,	   Size::byte}, {Reg::BP, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI} },

	/*01 110 000*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*01 110 001*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*01 110 010*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*01 110 011*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*01 110 100*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*01 110 101*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::BP,	Size::w_dword, RM::BP} },
	/*01 110 110*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::SI} },
	/*01 110 111*/{ {Mod::disp,	   Size::byte}, {Reg::SI, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI} },

	/*01 111 000*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*01 111 001*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*01 111 010*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*01 111 011*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*01 111 100*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*01 111 101*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::BP,	Size::w_dword, RM::BP} },
	/*01 111 110*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::SI,	Size::w_dword, RM::SI} },
	/*01 111 111*/{ {Mod::disp,	   Size::byte}, {Reg::DI, Size::b_w_dword}, {RM::DI,	Size::w_dword, RM::DI} },

	/*10 000 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 000 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 000 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 000 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 000 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::SIB,		Size::w_dword, RM::SP} },
	/*10 000 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 000 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 000 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::A, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },

	/*10 001 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 001 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 001 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 001 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 001 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::SIB,		Size::w_dword, RM::SP} },
	/*10 001 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 001 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 001 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::C, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },

	/*10 010 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 010 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 010 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 010 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 010 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::SIB,		Size::w_dword, RM::SP} },
	/*10 010 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 010 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 010 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::D, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },

	/*10 011 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 011 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 011 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 011 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 011 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::SIB,		Size::w_dword, RM::SP} },
	/*10 011 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 011 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 011 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::B, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },
								 
	/*10 100 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 100 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 100 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 100 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 100 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*10 100 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 100 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 100 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::SP, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },
								 
	/*10 101 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 101 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 101 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 101 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 101 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*10 101 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 101 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 101 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::BP, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },
							 
	/*10 110 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 110 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 110 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 110 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 110 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*10 110 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 110 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 110 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::SI, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },
	  
	/*10 111 000*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::A,		Size::w_dword, RM::A} },
	/*10 111 001*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::C,		Size::w_dword, RM::C} },
	/*10 111 010*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::D,		Size::w_dword, RM::D} },
	/*10 111 011*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::B,		Size::w_dword, RM::B} },
	/*10 111 100*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::SIB,	Size::w_dword, RM::SP} },
	/*10 111 101*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::BP,		Size::w_dword, RM::BP} },
	/*10 111 110*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::SI,		Size::w_dword, RM::SI} },
	/*10 111 111*/{ {Mod::disp,	   Size::w_dword}, {Reg::DI, Size::b_w_dword}, {RM::DI,		Size::w_dword, RM::DI} },


};